import bpy


from mathutils import Color


def create(obj):
    # generated by rigify.utils.write_metarig
    bpy.ops.object.mode_set(mode='EDIT')
    arm = obj.data

    for i in range(29):
        arm.rigify_layers.add()

    arm.rigify_layers[0].name = " "
    arm.rigify_layers[0].row = 1
    arm.rigify_layers[0].selset = False
    arm.rigify_layers[0].group = 0
    arm.rigify_layers[1].name = " "
    arm.rigify_layers[1].row = 1
    arm.rigify_layers[1].selset = False
    arm.rigify_layers[1].group = 0
    arm.rigify_layers[2].name = " "
    arm.rigify_layers[2].row = 1
    arm.rigify_layers[2].selset = False
    arm.rigify_layers[2].group = 0
    arm.rigify_layers[3].name = " "
    arm.rigify_layers[3].row = 1
    arm.rigify_layers[3].selset = False
    arm.rigify_layers[3].group = 0
    arm.rigify_layers[4].name = " "
    arm.rigify_layers[4].row = 1
    arm.rigify_layers[4].selset = False
    arm.rigify_layers[4].group = 0
    arm.rigify_layers[5].name = " "
    arm.rigify_layers[5].row = 1
    arm.rigify_layers[5].selset = False
    arm.rigify_layers[5].group = 0
    arm.rigify_layers[6].name = " "
    arm.rigify_layers[6].row = 1
    arm.rigify_layers[6].selset = False
    arm.rigify_layers[6].group = 0
    arm.rigify_layers[7].name = " "
    arm.rigify_layers[7].row = 1
    arm.rigify_layers[7].selset = False
    arm.rigify_layers[7].group = 0
    arm.rigify_layers[8].name = " "
    arm.rigify_layers[8].row = 1
    arm.rigify_layers[8].selset = False
    arm.rigify_layers[8].group = 0
    arm.rigify_layers[9].name = " "
    arm.rigify_layers[9].row = 1
    arm.rigify_layers[9].selset = False
    arm.rigify_layers[9].group = 0
    arm.rigify_layers[10].name = " "
    arm.rigify_layers[10].row = 1
    arm.rigify_layers[10].selset = False
    arm.rigify_layers[10].group = 0
    arm.rigify_layers[11].name = " "
    arm.rigify_layers[11].row = 1
    arm.rigify_layers[11].selset = False
    arm.rigify_layers[11].group = 0
    arm.rigify_layers[12].name = " "
    arm.rigify_layers[12].row = 1
    arm.rigify_layers[12].selset = False
    arm.rigify_layers[12].group = 0
    arm.rigify_layers[13].name = " "
    arm.rigify_layers[13].row = 1
    arm.rigify_layers[13].selset = False
    arm.rigify_layers[13].group = 0
    arm.rigify_layers[14].name = " "
    arm.rigify_layers[14].row = 1
    arm.rigify_layers[14].selset = False
    arm.rigify_layers[14].group = 0
    arm.rigify_layers[15].name = " "
    arm.rigify_layers[15].row = 1
    arm.rigify_layers[15].selset = False
    arm.rigify_layers[15].group = 0
    arm.rigify_layers[16].name = " "
    arm.rigify_layers[16].row = 1
    arm.rigify_layers[16].selset = False
    arm.rigify_layers[16].group = 0
    arm.rigify_layers[17].name = " "
    arm.rigify_layers[17].row = 1
    arm.rigify_layers[17].selset = False
    arm.rigify_layers[17].group = 0
    arm.rigify_layers[18].name = " "
    arm.rigify_layers[18].row = 1
    arm.rigify_layers[18].selset = False
    arm.rigify_layers[18].group = 0
    arm.rigify_layers[19].name = " "
    arm.rigify_layers[19].row = 1
    arm.rigify_layers[19].selset = False
    arm.rigify_layers[19].group = 0
    arm.rigify_layers[20].name = " "
    arm.rigify_layers[20].row = 1
    arm.rigify_layers[20].selset = False
    arm.rigify_layers[20].group = 0
    arm.rigify_layers[21].name = " "
    arm.rigify_layers[21].row = 1
    arm.rigify_layers[21].selset = False
    arm.rigify_layers[21].group = 0
    arm.rigify_layers[22].name = " "
    arm.rigify_layers[22].row = 1
    arm.rigify_layers[22].selset = False
    arm.rigify_layers[22].group = 0
    arm.rigify_layers[23].name = " "
    arm.rigify_layers[23].row = 1
    arm.rigify_layers[23].selset = False
    arm.rigify_layers[23].group = 0
    arm.rigify_layers[24].name = " "
    arm.rigify_layers[24].row = 1
    arm.rigify_layers[24].selset = False
    arm.rigify_layers[24].group = 0
    arm.rigify_layers[25].name = " "
    arm.rigify_layers[25].row = 1
    arm.rigify_layers[25].selset = False
    arm.rigify_layers[25].group = 0
    arm.rigify_layers[26].name = " "
    arm.rigify_layers[26].row = 1
    arm.rigify_layers[26].selset = False
    arm.rigify_layers[26].group = 0
    arm.rigify_layers[27].name = " "
    arm.rigify_layers[27].row = 1
    arm.rigify_layers[27].selset = False
    arm.rigify_layers[27].group = 0
    arm.rigify_layers[28].name = "Root"
    arm.rigify_layers[28].row = 14
    arm.rigify_layers[28].selset = False
    arm.rigify_layers[28].group = 0

    bones = {}

    bone = arm.edit_bones.new('Spine')
    bone.head = 0.0000, 0.0018, 0.8211
    bone.tail = 0.0000, -0.0442, 1.0134
    bone.roll = -0.0000
    bone.use_connect = False
    bones['Spine'] = bone.name
    bone = arm.edit_bones.new('Properties_Outfit_Default')
    bone.head = 0.0000, 0.2713, 0.0000
    bone.tail = 0.0000, 0.2713, 0.1046
    bone.roll = 0.0000
    bone.use_connect = False
    bones['Properties_Outfit_Default'] = bone.name
    bone = arm.edit_bones.new('Properties_Character_Template')
    bone.head = 0.0000, 0.2713, 0.1756
    bone.tail = 0.0000, 0.2713, 0.2802
    bone.roll = 0.0000
    bone.use_connect = False
    bones['Properties_Character_Template'] = bone.name
    bone = arm.edit_bones.new('Thigh.L')
    bone.head = 0.0816, -0.0215, 0.8559
    bone.tail = 0.0756, -0.0246, 0.4856
    bone.roll = 0.0164
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Spine']]
    bones['Thigh.L'] = bone.name
    bone = arm.edit_bones.new('Thigh.R')
    bone.head = -0.0816, -0.0215, 0.8559
    bone.tail = -0.0756, -0.0246, 0.4856
    bone.roll = -0.0164
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Spine']]
    bones['Thigh.R'] = bone.name
    bone = arm.edit_bones.new('RibCage')
    bone.head = 0.0000, -0.0442, 1.0134
    bone.tail = 0.0000, -0.0458, 1.1582
    bone.roll = -0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Spine']]
    bones['RibCage'] = bone.name
    bone = arm.edit_bones.new('Knee.L')
    bone.head = 0.0756, -0.0246, 0.4856
    bone.tail = 0.0657, -0.0042, 0.0775
    bone.roll = 0.0241
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Thigh.L']]
    bones['Knee.L'] = bone.name
    bone = arm.edit_bones.new('Knee.R')
    bone.head = -0.0756, -0.0246, 0.4856
    bone.tail = -0.0657, -0.0042, 0.0775
    bone.roll = -0.0241
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Thigh.R']]
    bones['Knee.R'] = bone.name
    bone = arm.edit_bones.new('Chest')
    bone.head = 0.0000, -0.0458, 1.1582
    bone.tail = 0.0000, -0.0148, 1.2805
    bone.roll = -0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['RibCage']]
    bones['Chest'] = bone.name
    bone = arm.edit_bones.new('Foot.L')
    bone.head = 0.0657, -0.0042, 0.0775
    bone.tail = 0.0689, -0.1086, 0.0249
    bone.roll = -0.0592
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Knee.L']]
    bones['Foot.L'] = bone.name
    bone = arm.edit_bones.new('Foot.R')
    bone.head = -0.0657, -0.0042, 0.0775
    bone.tail = -0.0689, -0.1086, 0.0249
    bone.roll = 0.0592
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Knee.R']]
    bones['Foot.R'] = bone.name
    bone = arm.edit_bones.new('Neck')
    bone.head = 0.0000, -0.0148, 1.2805
    bone.tail = 0.0000, -0.0277, 1.3921
    bone.roll = 0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Chest']]
    bones['Neck'] = bone.name
    bone = arm.edit_bones.new('Toes.L')
    bone.head = 0.0689, -0.1086, 0.0249
    bone.tail = 0.0697, -0.1838, 0.0046
    bone.roll = -0.0402
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Foot.L']]
    bones['Toes.L'] = bone.name
    bone = arm.edit_bones.new('AnklePivot.L')
    bone.head = 0.0657, 0.0495, 0.0213
    bone.tail = 0.0672, -0.0040, 0.0213
    bone.roll = 0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Foot.L']]
    bones['AnklePivot.L'] = bone.name
    bone = arm.edit_bones.new('Toes.R')
    bone.head = -0.0689, -0.1086, 0.0249
    bone.tail = -0.0697, -0.1838, 0.0046
    bone.roll = 0.0402
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Foot.R']]
    bones['Toes.R'] = bone.name
    bone = arm.edit_bones.new('AnklePivot.R')
    bone.head = -0.0657, 0.0495, 0.0213
    bone.tail = -0.0672, -0.0040, 0.0213
    bone.roll = -0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Foot.R']]
    bones['AnklePivot.R'] = bone.name
    bone = arm.edit_bones.new('Head')
    bone.head = 0.0000, -0.0277, 1.3921
    bone.tail = 0.0000, -0.0528, 1.6157
    bone.roll = -0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Neck']]
    bones['Head'] = bone.name
    bone = arm.edit_bones.new('Shoulder.L')
    bone.head = 0.0231, -0.0234, 1.2487
    bone.tail = 0.1131, 0.0042, 1.2508
    bone.roll = -0.0235
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Neck']]
    bones['Shoulder.L'] = bone.name
    bone = arm.edit_bones.new('Shoulder.R')
    bone.head = -0.0231, -0.0234, 1.2487
    bone.tail = -0.1131, 0.0042, 1.2508
    bone.roll = 0.0235
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Neck']]
    bones['Shoulder.R'] = bone.name
    bone = arm.edit_bones.new('Ponytail1')
    bone.head = 0.0000, 0.0860, 1.5697
    bone.tail = 0.0000, 0.1144, 1.5840
    bone.roll = -0.0000
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Head']]
    bones['Ponytail1'] = bone.name
    bone = arm.edit_bones.new('UpperArm.L')
    bone.head = 0.1131, 0.0042, 1.2508
    bone.tail = 0.3176, 0.0138, 1.2407
    bone.roll = -1.5214
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Shoulder.L']]
    bones['UpperArm.L'] = bone.name
    bone = arm.edit_bones.new('UpperArm.R')
    bone.head = -0.1131, 0.0042, 1.2508
    bone.tail = -0.3176, 0.0138, 1.2407
    bone.roll = 1.5214
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Shoulder.R']]
    bones['UpperArm.R'] = bone.name
    bone = arm.edit_bones.new('Ponytail2')
    bone.head = 0.0000, 0.1144, 1.5840
    bone.tail = 0.0000, 0.2405, 1.5840
    bone.roll = -0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Ponytail1']]
    bones['Ponytail2'] = bone.name
    bone = arm.edit_bones.new('Forearm.L')
    bone.head = 0.3176, 0.0138, 1.2407
    bone.tail = 0.5288, -0.0125, 1.2312
    bone.roll = -1.5260
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['UpperArm.L']]
    bones['Forearm.L'] = bone.name
    bone = arm.edit_bones.new('Forearm.R')
    bone.head = -0.3176, 0.0138, 1.2407
    bone.tail = -0.5288, -0.0125, 1.2312
    bone.roll = 1.5260
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['UpperArm.R']]
    bones['Forearm.R'] = bone.name
    bone = arm.edit_bones.new('Ponytail3')
    bone.head = 0.0000, 0.2405, 1.5840
    bone.tail = 0.0000, 0.3696, 1.5840
    bone.roll = -0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Ponytail2']]
    bones['Ponytail3'] = bone.name
    bone = arm.edit_bones.new('Wrist.L')
    bone.head = 0.5288, -0.0125, 1.2312
    bone.tail = 0.5842, -0.0197, 1.2286
    bone.roll = -1.5240
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Forearm.L']]
    bones['Wrist.L'] = bone.name
    bone = arm.edit_bones.new('Wrist.R')
    bone.head = -0.5288, -0.0125, 1.2312
    bone.tail = -0.5842, -0.0197, 1.2286
    bone.roll = 1.5240
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Forearm.R']]
    bones['Wrist.R'] = bone.name
    bone = arm.edit_bones.new('Ponytail4')
    bone.head = 0.0000, 0.3696, 1.5840
    bone.tail = 0.0000, 0.4935, 1.5840
    bone.roll = -0.0000
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Ponytail3']]
    bones['Ponytail4'] = bone.name
    bone = arm.edit_bones.new('Finger_Index_Carpal.L')
    bone.head = 0.5510, -0.0325, 1.2286
    bone.tail = 0.6007, -0.0463, 1.2230
    bone.roll = -2.8330
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Wrist.L']]
    bones['Finger_Index_Carpal.L'] = bone.name
    bone = arm.edit_bones.new('Finger_Middle_Carpal.L')
    bone.head = 0.5535, -0.0180, 1.2297
    bone.tail = 0.6071, -0.0271, 1.2246
    bone.roll = -3.0030
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Wrist.L']]
    bones['Finger_Middle_Carpal.L'] = bone.name
    bone = arm.edit_bones.new('Finger_Ring_Carpal.L')
    bone.head = 0.5556, -0.0044, 1.2291
    bone.tail = 0.6029, -0.0077, 1.2239
    bone.roll = -2.9853
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Wrist.L']]
    bones['Finger_Ring_Carpal.L'] = bone.name
    bone = arm.edit_bones.new('Finger_Pinky_Carpal.L')
    bone.head = 0.5569, 0.0092, 1.2258
    bone.tail = 0.5999, 0.0107, 1.2222
    bone.roll = -3.0077
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Wrist.L']]
    bones['Finger_Pinky_Carpal.L'] = bone.name
    bone = arm.edit_bones.new('Finger_Thumb1.L')
    bone.head = 0.5367, -0.0275, 1.2277
    bone.tail = 0.5652, -0.0578, 1.2124
    bone.roll = -1.0781
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Wrist.L']]
    bones['Finger_Thumb1.L'] = bone.name
    bone = arm.edit_bones.new('Finger_Index_Carpal.R')
    bone.head = -0.5510, -0.0325, 1.2286
    bone.tail = -0.6007, -0.0463, 1.2230
    bone.roll = 2.8330
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Wrist.R']]
    bones['Finger_Index_Carpal.R'] = bone.name
    bone = arm.edit_bones.new('Finger_Middle_Carpal.R')
    bone.head = -0.5535, -0.0180, 1.2297
    bone.tail = -0.6071, -0.0271, 1.2246
    bone.roll = 3.0030
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Wrist.R']]
    bones['Finger_Middle_Carpal.R'] = bone.name
    bone = arm.edit_bones.new('Finger_Ring_Carpal.R')
    bone.head = -0.5556, -0.0044, 1.2291
    bone.tail = -0.6029, -0.0077, 1.2239
    bone.roll = 2.9853
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Wrist.R']]
    bones['Finger_Ring_Carpal.R'] = bone.name
    bone = arm.edit_bones.new('Finger_Pinky_Carpal.R')
    bone.head = -0.5569, 0.0092, 1.2258
    bone.tail = -0.5999, 0.0107, 1.2222
    bone.roll = 3.0077
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Wrist.R']]
    bones['Finger_Pinky_Carpal.R'] = bone.name
    bone = arm.edit_bones.new('Finger_Thumb1.R')
    bone.head = -0.5367, -0.0275, 1.2277
    bone.tail = -0.5652, -0.0578, 1.2124
    bone.roll = 1.0781
    bone.use_connect = False
    bone.parent = arm.edit_bones[bones['Wrist.R']]
    bones['Finger_Thumb1.R'] = bone.name
    bone = arm.edit_bones.new('Finger_Index1.L')
    bone.head = 0.6007, -0.0463, 1.2230
    bone.tail = 0.6368, -0.0525, 1.2153
    bone.roll = -2.9282
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Index_Carpal.L']]
    bones['Finger_Index1.L'] = bone.name
    bone = arm.edit_bones.new('Finger_Middle1.L')
    bone.head = 0.6071, -0.0271, 1.2246
    bone.tail = 0.6475, -0.0321, 1.2149
    bone.roll = -2.9270
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Middle_Carpal.L']]
    bones['Finger_Middle1.L'] = bone.name
    bone = arm.edit_bones.new('Finger_Ring1.L')
    bone.head = 0.6029, -0.0077, 1.2239
    bone.tail = 0.6420, -0.0094, 1.2182
    bone.roll = -3.0045
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Ring_Carpal.L']]
    bones['Finger_Ring1.L'] = bone.name
    bone = arm.edit_bones.new('Finger_Pinky1.L')
    bone.head = 0.5999, 0.0107, 1.2222
    bone.tail = 0.6297, 0.0117, 1.2168
    bone.roll = -2.9675
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Pinky_Carpal.L']]
    bones['Finger_Pinky1.L'] = bone.name
    bone = arm.edit_bones.new('Finger_Thumb2.L')
    bone.head = 0.5652, -0.0578, 1.2124
    bone.tail = 0.5915, -0.0743, 1.1997
    bone.roll = -1.3263
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Thumb1.L']]
    bones['Finger_Thumb2.L'] = bone.name
    bone = arm.edit_bones.new('Finger_Index1.R')
    bone.head = -0.6007, -0.0463, 1.2230
    bone.tail = -0.6368, -0.0525, 1.2153
    bone.roll = 2.9282
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Index_Carpal.R']]
    bones['Finger_Index1.R'] = bone.name
    bone = arm.edit_bones.new('Finger_Middle1.R')
    bone.head = -0.6071, -0.0271, 1.2246
    bone.tail = -0.6475, -0.0321, 1.2149
    bone.roll = 2.9270
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Middle_Carpal.R']]
    bones['Finger_Middle1.R'] = bone.name
    bone = arm.edit_bones.new('Finger_Ring1.R')
    bone.head = -0.6029, -0.0077, 1.2239
    bone.tail = -0.6420, -0.0094, 1.2182
    bone.roll = 3.0045
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Ring_Carpal.R']]
    bones['Finger_Ring1.R'] = bone.name
    bone = arm.edit_bones.new('Finger_Pinky1.R')
    bone.head = -0.5999, 0.0107, 1.2222
    bone.tail = -0.6297, 0.0117, 1.2168
    bone.roll = 2.9675
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Pinky_Carpal.R']]
    bones['Finger_Pinky1.R'] = bone.name
    bone = arm.edit_bones.new('Finger_Thumb2.R')
    bone.head = -0.5652, -0.0578, 1.2124
    bone.tail = -0.5915, -0.0743, 1.1997
    bone.roll = 1.3263
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Thumb1.R']]
    bones['Finger_Thumb2.R'] = bone.name
    bone = arm.edit_bones.new('Finger_Index2.L')
    bone.head = 0.6368, -0.0525, 1.2153
    bone.tail = 0.6578, -0.0565, 1.2068
    bone.roll = -2.6468
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Index1.L']]
    bones['Finger_Index2.L'] = bone.name
    bone = arm.edit_bones.new('Finger_Middle2.L')
    bone.head = 0.6475, -0.0321, 1.2149
    bone.tail = 0.6681, -0.0349, 1.2072
    bone.roll = -2.7470
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Middle1.L']]
    bones['Finger_Middle2.L'] = bone.name
    bone = arm.edit_bones.new('Finger_Ring2.L')
    bone.head = 0.6420, -0.0094, 1.2182
    bone.tail = 0.6648, -0.0108, 1.2108
    bone.roll = -2.7904
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Ring1.L']]
    bones['Finger_Ring2.L'] = bone.name
    bone = arm.edit_bones.new('Finger_Pinky2.L')
    bone.head = 0.6297, 0.0117, 1.2168
    bone.tail = 0.6454, 0.0117, 1.2115
    bone.roll = -2.7966
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Pinky1.L']]
    bones['Finger_Pinky2.L'] = bone.name
    bone = arm.edit_bones.new('Finger_Thumb3.L')
    bone.head = 0.5915, -0.0743, 1.1997
    bone.tail = 0.6113, -0.0857, 1.1906
    bone.roll = -1.2803
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Thumb2.L']]
    bones['Finger_Thumb3.L'] = bone.name
    bone = arm.edit_bones.new('Finger_Index2.R')
    bone.head = -0.6368, -0.0525, 1.2153
    bone.tail = -0.6578, -0.0565, 1.2068
    bone.roll = 2.6468
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Index1.R']]
    bones['Finger_Index2.R'] = bone.name
    bone = arm.edit_bones.new('Finger_Middle2.R')
    bone.head = -0.6475, -0.0321, 1.2149
    bone.tail = -0.6681, -0.0349, 1.2072
    bone.roll = 2.7470
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Middle1.R']]
    bones['Finger_Middle2.R'] = bone.name
    bone = arm.edit_bones.new('Finger_Ring2.R')
    bone.head = -0.6420, -0.0094, 1.2182
    bone.tail = -0.6648, -0.0108, 1.2108
    bone.roll = 2.7904
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Ring1.R']]
    bones['Finger_Ring2.R'] = bone.name
    bone = arm.edit_bones.new('Finger_Pinky2.R')
    bone.head = -0.6297, 0.0117, 1.2168
    bone.tail = -0.6454, 0.0117, 1.2115
    bone.roll = 2.7966
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Pinky1.R']]
    bones['Finger_Pinky2.R'] = bone.name
    bone = arm.edit_bones.new('Finger_Thumb3.R')
    bone.head = -0.5915, -0.0743, 1.1997
    bone.tail = -0.6113, -0.0857, 1.1906
    bone.roll = 1.2803
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Thumb2.R']]
    bones['Finger_Thumb3.R'] = bone.name
    bone = arm.edit_bones.new('Finger_Index3.L')
    bone.head = 0.6578, -0.0565, 1.2068
    bone.tail = 0.6810, -0.0605, 1.1971
    bone.roll = -2.5972
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Index2.L']]
    bones['Finger_Index3.L'] = bone.name
    bone = arm.edit_bones.new('Finger_Middle3.L')
    bone.head = 0.6681, -0.0349, 1.2072
    bone.tail = 0.6950, -0.0385, 1.1977
    bone.roll = -2.7355
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Middle2.L']]
    bones['Finger_Middle3.L'] = bone.name
    bone = arm.edit_bones.new('Finger_Ring3.L')
    bone.head = 0.6648, -0.0108, 1.2108
    bone.tail = 0.6908, -0.0126, 1.2003
    bone.roll = -2.7701
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Ring2.L']]
    bones['Finger_Ring3.L'] = bone.name
    bone = arm.edit_bones.new('Finger_Pinky3.L')
    bone.head = 0.6454, 0.0117, 1.2115
    bone.tail = 0.6663, 0.0114, 1.2037
    bone.roll = -2.9399
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Pinky2.L']]
    bones['Finger_Pinky3.L'] = bone.name
    bone = arm.edit_bones.new('Finger_Index3.R')
    bone.head = -0.6578, -0.0565, 1.2068
    bone.tail = -0.6810, -0.0605, 1.1971
    bone.roll = 2.5972
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Index2.R']]
    bones['Finger_Index3.R'] = bone.name
    bone = arm.edit_bones.new('Finger_Middle3.R')
    bone.head = -0.6681, -0.0349, 1.2072
    bone.tail = -0.6950, -0.0385, 1.1977
    bone.roll = 2.7355
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Middle2.R']]
    bones['Finger_Middle3.R'] = bone.name
    bone = arm.edit_bones.new('Finger_Ring3.R')
    bone.head = -0.6648, -0.0108, 1.2108
    bone.tail = -0.6908, -0.0126, 1.2003
    bone.roll = 2.7701
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Ring2.R']]
    bones['Finger_Ring3.R'] = bone.name
    bone = arm.edit_bones.new('Finger_Pinky3.R')
    bone.head = -0.6454, 0.0117, 1.2115
    bone.tail = -0.6663, 0.0114, 1.2037
    bone.roll = 2.9399
    bone.use_connect = True
    bone.parent = arm.edit_bones[bones['Finger_Pinky2.R']]
    bones['Finger_Pinky3.R'] = bone.name

    bpy.ops.object.mode_set(mode='OBJECT')
    pbone = obj.pose.bones[bones['Spine']]
    pbone.rigify_type = 'cloud_spine'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'XYZ'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.deform_segments = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.bbone_segments = 6
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.sharp_sections = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.display_scale = 1.0
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.cap_control = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.shape_key_helpers = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Properties_Outfit_Default']]
    pbone.rigify_type = 'basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True]
    try:
        pbone.rigify_parameters.make_control = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_deform = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Properties_Character_Template']]
    pbone.rigify_type = 'basic.raw_copy'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True]
    try:
        pbone.rigify_parameters.make_control = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.make_deform = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.relink_constraints = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Thigh.L']]
    pbone.rigify_type = 'cloud_limbs'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.type = "LEG"
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.rotation_axis = "automatic"
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.cap_control = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.display_scale = 1.2000000476837158
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.lock_yz = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Thigh.R']]
    pbone.rigify_type = 'cloud_limbs'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.type = "LEG"
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.cap_control = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.display_scale = 1.2000000476837158
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.lock_yz = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['RibCage']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Knee.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Knee.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Chest']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Foot.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Foot.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Neck']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Toes.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['AnklePivot.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Toes.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['AnklePivot.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Head']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Shoulder.L']]
    pbone.rigify_type = 'cloud_shoulder'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.display_scale = 1.5
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.deform_segments = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.cap_control = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.sharp_sections = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Shoulder.R']]
    pbone.rigify_type = 'cloud_shoulder'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.display_scale = 1.5
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.cap_control = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.sharp_sections = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.deform_segments = 1
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Ponytail1']]
    pbone.rigify_type = 'cloud_fk_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.deform_segments = 1
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.sharp_sections = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['UpperArm.L']]
    pbone.rigify_type = 'cloud_limbs'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.cap_control = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.bbone_segments = 10
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.world_aligned = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.display_scale = 1.0
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.lock_yz = True
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.shape_key_helpers = False
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['UpperArm.R']]
    pbone.rigify_type = 'cloud_limbs'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.cap_control = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.bbone_segments = 10
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.world_aligned = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.lock_yz = True
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Ponytail2']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Forearm.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Forearm.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Ponytail3']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Wrist.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Wrist.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Ponytail4']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'QUATERNION'
    pbone.bone.layers = [True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Index_Carpal.L']]
    pbone.rigify_type = 'cloud_fk_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.deform_segments = 1
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Finger_Middle_Carpal.L']]
    pbone.rigify_type = 'cloud_fk_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.deform_segments = 1
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Finger_Ring_Carpal.L']]
    pbone.rigify_type = 'cloud_fk_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.deform_segments = 1
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Finger_Pinky_Carpal.L']]
    pbone.rigify_type = 'cloud_fk_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.deform_segments = 1
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Finger_Thumb1.L']]
    pbone.rigify_type = 'cloud_fk_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'ZXY'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.shape_key_helpers = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.deform_segments = 1
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Finger_Index_Carpal.R']]
    pbone.rigify_type = 'cloud_fk_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.deform_segments = 1
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Finger_Middle_Carpal.R']]
    pbone.rigify_type = 'cloud_fk_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.deform_segments = 1
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Finger_Ring_Carpal.R']]
    pbone.rigify_type = 'cloud_fk_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.deform_segments = 1
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Finger_Pinky_Carpal.R']]
    pbone.rigify_type = 'cloud_fk_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.deform_segments = 1
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Finger_Thumb1.R']]
    pbone.rigify_type = 'cloud_fk_chain'
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'ZXY'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    try:
        pbone.rigify_parameters.shape_key_helpers = False
    except AttributeError:
        pass
    try:
        pbone.rigify_parameters.deform_segments = 1
    except AttributeError:
        pass
    pbone = obj.pose.bones[bones['Finger_Index1.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Middle1.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Ring1.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Pinky1.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Thumb2.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Index1.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Middle1.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Ring1.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Pinky1.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Thumb2.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Index2.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Middle2.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Ring2.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Pinky2.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Thumb3.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Index2.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Middle2.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Ring2.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Pinky2.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Thumb3.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Index3.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Middle3.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Ring3.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Pinky3.L']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Index3.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Middle3.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Ring3.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]
    pbone = obj.pose.bones[bones['Finger_Pinky3.R']]
    pbone.rigify_type = ''
    pbone.lock_location = (False, False, False)
    pbone.lock_rotation = (False, False, False)
    pbone.lock_rotation_w = False
    pbone.lock_scale = (False, False, False)
    pbone.rotation_mode = 'YZX'
    pbone.bone.layers = [False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False]

    bpy.ops.object.mode_set(mode='EDIT')
    for bone in arm.edit_bones:
        bone.select = False
        bone.select_head = False
        bone.select_tail = False
    for b in bones:
        bone = arm.edit_bones[bones[b]]
        bone.select = True
        bone.select_head = True
        bone.select_tail = True
        bone.bbone_x = bone.bbone_z = bone.length * 0.05
        arm.edit_bones.active = bone

    arm.layers = [(x in [0, 5, 31]) for x in range(32)]

    return bones

if __name__ == "__main__":
    create(bpy.context.active_object)
